/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class SystemAudioBuffer {
  constructor(options?: BufferOptions | undefined | null)
  /**
   * Begin capturing. Nothing records until this is called.
   *
   * On macOS this triggers the System Audio Recording prompt. A denial
   * resolves successfully and accumulates no audio, so poll
   * `status().filledMs` for a second to tell the difference.
   */
  start(): void
  /** Stop capturing and discard the contents. */
  stop(): void
  /**
   * Stop capturing but keep the contents, for examining and cutting.
   *
   * Audio playing during a freeze is not recorded.
   */
  freeze(): void
  /**
   * Resume capturing after a freeze, starting from empty.
   *
   * Contents are cleared rather than appended to: keeping them would leave an
   * invisible discontinuity mid-window, so every position in a waveform drawn
   * over it would be wrong.
   */
  resume(): void
  /**
   * A snapshot of what the buffer is doing.
   *
   * Device facts come from the supervisor, not from `start()`, since the
   * device can change underneath a running capture.
   *
   * # Errors
   *
   * If a thread panicked while holding the buffer.
   */
  status(): BufferStatus
  /** Dismiss a latched error. A successful automatic recovery clears it too. */
  clearError(): void
  /**
   * Change how much history to keep, without reallocating.
   *
   * Lowering it hides older audio; raising it back reveals whatever is still
   * physically present, up to the ceiling set at construction.
   */
  setRetentionSeconds(seconds: number): void
  /**
   * Cut a range out as a mono 16-bit WAV.
   *
   * Offsets are milliseconds from the oldest audio held. Out-of-range values
   * clamp. A container rather than raw PCM so format sniffers accept it and
   * the bytes play in an `<audio>` element unchanged.
   */
  read(startMs: number, endMs: number): Buffer
  /**
   * Waveform envelope: `[min, max]` per bucket, interleaved and normalised to
   * -1.0..=1.0, so the array is `buckets * 2` long. Computed here so drawing
   * costs a few thousand floats rather than the whole buffer.
   */
  peaks(buckets: number): Float32Array
  /**
   * Whether the OS will allow system audio capture.
   *
   * `notRequired` on Windows and Linux; `unknown` on macOS unless built with
   * the `tcc-preflight` feature.
   */
  permissionStatus(): PermissionStatus
}

export interface BufferOptions {
  /** How much history to keep. Defaults to 900 (15 minutes). */
  retentionSeconds?: number
  /** Output rate. Defaults to 16000, which is what Whisper-style models want. */
  targetSampleRate?: number
  /**
   * Allocation ceiling. `retentionSeconds` can be raised up to this at
   * runtime without reallocating. Defaults to 3600.
   */
  ceilingSeconds?: number
}

export declare const enum BufferState {
  /** Not capturing. Nothing is being recorded. */
  Idle = 'idle',
  /** Capturing into the rolling window. */
  Running = 'running',
  /** Capture stopped, contents retained for reading. */
  Frozen = 'frozen'
}

export interface BufferStatus {
  state: BufferState
  /**
   * Audio currently held, in milliseconds. Wall-clock accurate: gaps in the
   * device's delivery are filled with silence rather than closed up.
   */
  filledMs: number
  /** The active retention window, in milliseconds. */
  retentionMs: number
  /** Output rate of everything `read()` returns. */
  sampleRate: number
  /**
   * How much of the buffer is synthesised silence standing in for a gap in
   * device delivery. Nonzero is normal on Windows during quiet passages.
   */
  silenceInsertedMs: number
  /**
   * The device rate being captured, once running. Can change mid-capture if
   * the default output device changes.
   */
  nativeSampleRate?: number
  channels?: number
  deviceName?: string
  /**
   * How many times the stream has been rebuilt after a device fault or
   * change. Recording continues across these; the buffer is preserved.
   */
  restarts: number
  /**
   * The last error, **latched**. Persists until `clearError()` or a
   * successful automatic recovery, so polling cannot miss it.
   */
  error?: string
}

/**
 * Whether this platform needs a permission grant for loopback capture, without
 * constructing a buffer first.
 */
export declare function permissionStatus(): PermissionStatus

export declare const enum PermissionStatus {
  Granted = 'granted',
  Denied = 'denied',
  /** macOS without preflight: knowable only by attempting capture. */
  Unknown = 'unknown',
  /** Windows and Linux: loopback needs no permission. */
  NotRequired = 'notRequired'
}
